version: "3.9"

services:
  ibanking-ui:
    build:
      context: .
      dockerfile: Dockerfile
    image: ibanking-ui:latest
    container_name: ibanking-ui
    ports:
      - "2000:80"
    restart: unless-stopped
